/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazVendedor;

import DAO.Conexion;
import Negocio.Producto;
import java.awt.event.ItemEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;
import mysql.Conector;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Ian Quiroga
 */
public class vendedorProducts extends javax.swing.JInternalFrame {

    ArrayList<Integer> lista_id = new ArrayList<Integer>();
    JDesktopPane escritorio = null;// arreglo de los ids a rescatar 
        Calendar fecha = new GregorianCalendar();
        //Obtenemos el valor del año, mes, día,
        //hora, minuto y segundo del sistema
        //usando el método get y el parámetro correspondiente
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        int dia = fecha.get(Calendar.DAY_OF_MONTH); 
        
     
      



    String tipoPago=" ";
    String cuotasCredito=" "; 

    String[] titulos = {"Nombre", "Talla", "Cantidad","Precio","Sub Total"};
    DefaultTableModel model = new DefaultTableModel(null, titulos);
    int contador=0; 
    
    public vendedorProducts(JDesktopPane escritorio) {

        initComponents();
        this.escritorio = escritorio; 
        cuotas.setVisible(false);

    }
    private static java.sql.Date getCurrentDate() {
    java.util.Date today = new java.util.Date();
    return new java.sql.Date(today.getTime());
}

    
        void InsertarVenta(int fecha, String observacion, int usuario, int montoTotal, String tipoPago, String numeroBoleta, int numeroCuotas) throws SQLException {

        Conector c = new Conector();

        String insert1 = "insert into venta  values ('" + fecha + "','" + observacion + "','" + usuario + "','" + montoTotal + "','" + tipoPago + "')";

        String insert = "INSERT INTO venta"
                + "(fecha, observacion, Vendedor_idVendedor, montoTotal,tipoPago,numeroBoleta,numeroCuotas) VALUES"
                + "(?,?,?,?,?,?,?)";
        PreparedStatement pst = c.conexion.prepareStatement(insert);
        pst.setInt(1 ,fecha);
        pst.setString(2, observacion);
        pst.setInt(3, usuario);
        pst.setDouble(4, montoTotal);
        pst.setString(5, tipoPago);
        pst.setString(6, numeroBoleta);
        pst.setInt(7, numeroCuotas);
        pst.executeUpdate(); 
        
        
       

        //falta mensaje de exito y validar contraseña y que no exista el usuario
        //this.dispose(); //cierro ventana mas pequeña. 

    } 
    
        
            void InsertarDettalleVenta(int cantidad, int idVenta, int idProducto, int valorUnitario,int valorSubtotal) throws SQLException {

        Conector c = new Conector();

        //String insert1 = "insert into venta  values ('" + fecha + "','" + observacion + "','" + usuario + "','" + montoTotal + "','" + tipoPago + "')";

        String insert = "INSERT INTO detalleventa"
                + "(cantidad, Venta_idVenta, Producto_N_producto, valorUnitario, subTotal) VALUES"
                + "(?,?,?,?,?)";
        PreparedStatement pst = c.conexion.prepareStatement(insert);
        pst.setInt(1,cantidad);
        pst.setInt(2, idVenta);
        pst.setInt(3, idProducto);
        pst.setInt(4, valorUnitario);
        pst.setInt(5, valorSubtotal);
        
        pst.executeUpdate();

        //falta mensaje de exito y validar contraseña y que no exista el usuario
        //this.dispose(); //cierro ventana mas pequeña. 

    }     
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        codigoBarra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        categoria = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Efectivo = new javax.swing.JCheckBox();
        Debito = new javax.swing.JCheckBox();
        Credito = new javax.swing.JCheckBox();
        cuotas = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtnumeroBoleta = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar Productos");
        setPreferredSize(new java.awt.Dimension(800, 580));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/codigo.png"))); // NOI18N
        jLabel3.setText("Código Barra :");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/categoria.jpg"))); // NOI18N
        jLabel4.setText("Descuento:");

        categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Accesorio", "Babero", "Mantas", "Porta Bebé", "Ropa", "Set Cuna", "Zapato Americano", "Zapato Chino", " " }));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoPrecio.jpg"))); // NOI18N
        jLabel5.setText("Cantidad:");

        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto ", "Talla", "Precio", "Sub Total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(codigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(codigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconoPrecio.jpg"))); // NOI18N
        jLabel6.setText("Total:");

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de Pago:");

        Efectivo.setText("Efectivo");
        Efectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EfectivoActionPerformed(evt);
            }
        });

        Debito.setText("Debito");
        Debito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebitoActionPerformed(evt);
            }
        });

        Credito.setText("Credito");
        Credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditoActionPerformed(evt);
            }
        });

        cuotas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 Cuota ", "2 Cuotas", "3 Cuotas ", "4 Cuotas ", "5 Cuotas ", "6 Cuotas ", "7 Cuotas", "8 Cuotas ", "9 Cuotas ", "10 Cuotas", "11 Cuotas ", "12 Cuotas" }));
        cuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuotasActionPerformed(evt);
            }
        });

        jLabel7.setText("Nº de Boleta o Voucher");

        txtnumeroBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumeroBoletaActionPerformed(evt);
            }
        });

        jButton2.setText("VENDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addGap(295, 295, 295)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Debito)
                                    .addComponent(Efectivo)
                                    .addComponent(Credito)
                                    .addComponent(cuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtnumeroBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addComponent(Efectivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Debito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Credito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnumeroBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(9, 9, 9))
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

      
        
        try {
            // TODO add your handling code here:

            Conector c = new Conector();
            String cod = codigoBarra.getText();

            String cant = cantidad.getText();
         
           
            String consulta = "select N_producto, nombre, talla, color, valorVenta,stockTienda, stockBodega from producto where N_producto > 0";
            Boolean bool = false;

            if (!cod.equals(" ") && !cod.equals("")) {

                consulta = consulta + " AND codigoBarra=" + cod;
                bool = true;

            }

            if (bool = true) {

                PreparedStatement ps = c.conexion.prepareStatement(consulta);
                ResultSet rs = ps.executeQuery();

                String[] fila = new String[5];

                while (rs.next()) {

                    fila[0] = rs.getString("nombre");
                    fila[1] = rs.getString("talla");
                    
                    int valor = rs.getInt("valorVenta"); 
                    
                    int subtotal=valor*Integer.parseInt(cant);
                    String valor1 = Integer.toString(valor);
                    fila[2] = cant;
                    fila[3] = valor1; 
                    fila[4]= Integer.toString(subtotal);
                    contador=contador+subtotal;
                    System.out.println("valor" + fila[3]);
                    model.addRow(fila);

                }
                jTable1.setModel(model);
                total.setText(Integer.toString(contador));
                System.out.println("TOTAL"+contador);
            }

            /*  
             if (!cod.equals(" ") && !cod.equals("")){
               
             consulta=consulta + " AND codigoBarra=" + cod;
             bool=true;
               
             }
           
             consulta= consulta +";";
           
             if (bool = true){
               
             try {
                   
             DefaultTableModel dm = (DefaultTableModel)tablas.getModel();
                   
             int rowCount = dm.getRowCount();
             //Remove rows one by one from the end of the table
             for (int i = rowCount - 1; i >= 0; i--) {
             dm.removeRow(i);
             }
                   
             Producto.rescatarProducto(consulta, tablas, lista_id);
             //this.dispose();
                   
             } catch (SQLException ex) {
             Logger.getLogger(vendedorProducts.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Ha ocurrido un problema."," ",JOptionPane.ERROR_MESSAGE);
                   
                   
             }
               
             }
           
             else{
               
             JOptionPane.showMessageDialog(null, "Debe ingresar un campo para buscar.");
             }
             */
        } catch (SQLException ex) {
            Logger.getLogger(vendedorProducts.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int fsel;
        int rep;

        try {

            fsel = jTable1.getSelectedRow();

            if (fsel == -1) {
                JOptionPane.showMessageDialog(null, "debe seleccionar producto a eliminar");

            } else {
                DefaultTableModel temp = (DefaultTableModel) jTable1.getModel();

                rep = JOptionPane.showConfirmDialog(null, "¿Eliminar?", "eliminar", JOptionPane.YES_NO_OPTION);

                if (rep == JOptionPane.YES_NO_OPTION) {
                    temp.removeRow(fsel);
                }
            }

        } catch (Exception e) {
        }


    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void EfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EfectivoActionPerformed
        // TODO add your handling code here:
         cuotas.setVisible(false);
         Credito.setSelected(false);
         Debito.setSelected(false);  
         
         
         if(Efectivo.isSelected()){
            
         tipoPago="Efectivo";
         }
    }//GEN-LAST:event_EfectivoActionPerformed

    private void DebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebitoActionPerformed
        // TODO add your handling code here:
        cuotas.setVisible(false);
        Credito.setSelected(false);
         Efectivo.setSelected(false);
         
         if(Debito.isSelected()){ 
             
             tipoPago="Debito";
         
         
         }
    }//GEN-LAST:event_DebitoActionPerformed

    private void cuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuotasActionPerformed
        // TODO add your handling code here: 
        
        
        
        
        
    }//GEN-LAST:event_cuotasActionPerformed

    private void CreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditoActionPerformed
        // TODO add your handling code here:
        
        cuotas.setVisible(true); 
        Efectivo.setSelected(false);
         Debito.setSelected(false);
         
         if(Credito.isSelected()){
         
          tipoPago="Credito"; 
         }
         
    }//GEN-LAST:event_CreditoActionPerformed

    private void txtnumeroBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumeroBoletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeroBoletaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: 
        
        if( (!Debito.isSelected() && !Efectivo.isSelected() && !Credito.isSelected()  )){
           JOptionPane.showMessageDialog(rootPane, "Ingrese Numero de Boleta o Seleccione Tipo de Pago"); 
           
           //hacer validacion de numeroBoleta distinto a vacio 
        
        }else { 
            System.out.println("fecha"+año+mes+dia);
           String numero= txtnumeroBoleta.getText(); 
           
           int cuotas2 = cuotas.getSelectedIndex();
           cuotas2= cuotas2+1;
           if(tipoPago.equals("Efectivo")|| tipoPago.equals("Debito")){
           cuotas2=0;
           
           } 
           
         
            try {
                InsertarVenta(20151007, "observacion",1,contador, tipoPago,numero, cuotas2); 
                
                int rowCount=jTable1.getRowCount();
                
                for(int i=rowCount-1 ; i>=0 ;i--){
                
                 jTable1.getValueAt(i, 2); //cantidad
                 jTable1.getValueAt(i, 3); //preciouniratio
                 jTable1.getValueAt(i, 4); //subtotal
                InsertarDettalleVenta( Integer.parseInt(jTable1.getValueAt(i, 2).toString()), 1, 1,  Integer.parseInt(jTable1.getValueAt(i, 3).toString()), Integer.parseInt(jTable1.getValueAt(i, 4).toString()));
                
                }
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(vendedorProducts.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
            
            
        
        
        }  
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    public String[] getTalla(String talla) {

        if (talla.equals("Ropa") || talla.equals("Accesorio")) {

            String[] combo1 = new String[17];

            combo1[0] = "OS";
            combo1[1] = "NB";
            combo1[2] = "0-3 Meses";
            combo1[3] = "3 Meses";
            combo1[4] = "3-6 Meses";
            combo1[5] = "6 Meses";
            combo1[6] = "6-9 Meses";
            combo1[7] = "9 Meses";
            combo1[8] = "9-12 Meses";
            combo1[9] = "12 Meses";
            combo1[10] = "18 Meses";
            combo1[11] = "24 Meses";
            combo1[12] = "3";
            combo1[13] = "4";
            combo1[14] = "5";
            combo1[15] = "6";
            combo1[16] = "7";

            return combo1;

        } else if (talla.equals("Zapato Americano")) {

            String[] combo2 = new String[10];

            combo2[0] = "2";
            combo2[1] = "3";
            combo2[2] = "4";
            combo2[3] = "5";
            combo2[4] = "6";
            combo2[5] = "7";
            combo2[6] = "8";
            combo2[7] = "9";
            combo2[8] = "10";
            combo2[9] = "11";

            return combo2;

        } else if (talla.equals("Zapato Chino")) {

            String[] combo2 = new String[7];

            combo2[0] = "15";
            combo2[1] = "16";
            combo2[2] = "17";
            combo2[3] = "18";
            combo2[4] = "19";
            combo2[5] = "20";
            combo2[6] = "21";

            return combo2;

        } else {

            String[] combo = new String[1];
            combo[0] = "OS";

            return combo;

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Credito;
    private javax.swing.JCheckBox Debito;
    private javax.swing.JCheckBox Efectivo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JComboBox categoria;
    private javax.swing.JTextField codigoBarra;
    private javax.swing.JComboBox cuotas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField total;
    private javax.swing.JTextField txtnumeroBoleta;
    // End of variables declaration//GEN-END:variables
}
